name: 'Perform SAST scan'
description: 'Perform a SAST scan on Fortify on Demand'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: ./internal/set-fod-var-defaults@main
    - uses: ./setup@main
      with:
        export-path: false
        fcli: action-default
    - uses: ./internal/fod-login@main
    - uses: ./package@main
    - uses: ./internal/run-script@main
      with:
        script: fod-scan.sh
      env: 
        DO_SAST_SCAN: true # Not used for now
        GITHUB_TOKEN: ${{ github.token }}
    - if: env.DO_EXPORT == 'true'
      uses: ./fod-export@main
        
branding:
  icon: 'shield'
  color: 'blue'

