name: 'Perform SAST scan'
description: 'Perform a SAST scan on ScanCentral SAST'
author: 'Fortify'
runs:
  using: composite
  steps:
    - uses: $NewAction/internal/set-ssc-var-defaults@main
    - uses: $NewAction/setup@main
      with:
        export-path: false
        fcli: action-default
        debricked-cli: ${{ env.DO_DEBRICKED_SCAN=='true' && 'action-default' || 'skip' }}
    - uses: $NewAction/internal/ssc-login@main
    - uses: $NewAction/package@main
    - uses: $NewAction/internal/run-script@main
      with:
        script: sc-sast-and-debricked-scan.sh
      env: 
        DO_SC_SAST_SCAN: true
        GITHUB_TOKEN: ${{ github.token }}
    - if: env.DO_EXPORT == 'true'
      uses: $NewAction/ssc-export@main
        
branding:
  icon: 'shield'
  color: 'blue'


